namespace:
  name: staging

replicaCount: 1
 
image:
  repository: nginx
  tag: 1.18.0
  pullPolicy: IfNotPresent

resources:
  memory: 128Mi
  cpu: 50m

service:
  port: 8112
  type: ClusterIP

configmap:
  version: 1.18.0